Nhj input flex
kids-first/kf-somatic-workflow pull request #102
Opened 2021-04-08 19:18 UTC by NHJohnson

## Description

This is adding some more flexibility to the inputs of the somatic consensus workflow. 

Fixes # https://github.com/d3b-center/bixu-tracker/issues/1021

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have committed any related changes to the PR

2021-04-12 15:31 UTC, migbro requested changes
We can talk about this a bit this afternoon, your approach addresses most of what I was looking for, but also ends up taking away a bit of flexibility in the `variant_filter` step for the `filter_expression` inputs

2021-04-12 15:31 UTC, migbro commented on workflow/kfdrc_consensus_calling.cwl
> +  frequency_upperbound: {type: string?, default: '0.001', doc: "Population allele frequency above which to apply frequency filter"}
This should be changed to float, and value should be `0.001` with no quotes. In the context of passing to the tool itself in the workflow, it'll still be interpreted correctly.

2021-04-12 15:31 UTC, migbro commented on workflow/kfdrc_consensus_calling.cwl
> +      retain_info: maf_retain_info
I am also working on adding an optional `retain_fmt` input, but that should probably be a seperate PR

2021-04-29 19:38 UTC, NHJohnson commented
Most of the desired features of this PR got integrated into a different PR and merged, so I'm going to delete this one.

2021-04-29 19:38 UTC, closed without merging