🐛  Hotifx sample swap issues
kids-first/kf-somatic-workflow pull request #156
Opened 2023-08-21 18:46 UTC by dmiller15

## Description

As defined https://github.com/d3b-center/bixu-tracker/issues/2049 we're experiencing sample swapping when using the old_tumor/normal_name inputs. These changes make the renaming process error proof as we're now matching the new samples to the old ones before swapping.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Previously erroneous run now works: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/39ffe06d-de74-4ea2-97b9-25f89a8d3848/#

Compare the results in above against the pre-swap intermediates found here: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/files/#q?page=1&label_id=swap

```
### MANTA 

BEFORE
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  1224650_D1      1182220_D1
AFTER
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  BS_24RR82Q8     BS_PD37THK0

### Strelka2

BEFORE
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NORMAL  TUMOR
AFTER
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  BS_24RR82Q8     BS_PD37THK0

### Mutect2

BEFORE
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  1182220_D1      1224650_D1
AFTER
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  BS_PD37THK0     BS_24RR82Q8

### Lancet

BEFORE
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  1182220_D1      1224650_D1
AFTER
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  BS_PD37THK0     BS_24RR82Q8

### Vardict

BEFORE
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  1182220_D1      1224650_D1
AFTER
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  BS_PD37THK0     BS_24RR82Q8
```

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have committed any related changes to the PR

2023-08-21 19:33 UTC, migbro requested changes
Some typos and a possible bug in logic. Still not sure though how the changes catch the issue in which the sort step might reorder the samples...

2023-08-21 19:33 UTC, migbro commented on sub_workflows/kfdrc_manta_sub_wf.cwl
> +    when: $(inputs.old_tumor_name != null && inputs.old_tumor_name != null)
These say the same thing - maybe you meant and normal?

2023-08-21 19:33 UTC, migbro commented on sub_workflows/kfdrc_vardict_sub_wf.cwl
> +    when: $(inputs.old_tumor_name != null && inputs.old_tumor_name != null)
Same comment as for manta sub

2023-08-21 19:33 UTC, migbro commented on workflow/kfdrc_production_lancet_wf.cwl
> +  old_tumor_name: { type: 'string?', doc: "If `SM:` sample name in te align file is different than `input_tumor_name`, you **must** provide it here"}
typo - `te` should be `the`

2023-08-21 19:33 UTC, migbro commented on workflow/kfdrc_production_manta_wf.cwl
> +  old_tumor_name: { type: 'string?', doc: "If `SM:` sample name in te align file is different than `input_tumor_name`, you **must** provide it here"}
same typo

2023-08-21 19:39 UTC, dmiller15 commented on workflow/kfdrc_production_lancet_wf.cwl
> +  old_tumor_name: { type: 'string?', doc: "If `SM:` sample name in te align file is different than `input_tumor_name`, you **must** provide it here"}
Got it

2023-08-21 19:39 UTC, dmiller15 commented on workflow/kfdrc_production_manta_wf.cwl
> +  old_tumor_name: { type: 'string?', doc: "If `SM:` sample name in te align file is different than `input_tumor_name`, you **must** provide it here"}
It was everywhere!

2023-08-21 19:39 UTC, dmiller15 commented on sub_workflows/kfdrc_vardict_sub_wf.cwl
> +    when: $(inputs.old_tumor_name != null && inputs.old_tumor_name != null)
Got it.

2023-08-21 19:46 UTC, dmiller15 commented
@migbro The way this works is that the new tool uses the secondary methodology for `bcftools reheader --sample`: https://samtools.github.io/bcftools/bcftools.html#reheader

> new sample names, one name per line, in the same order as they appear in the VCF file. Alternatively, only samples which need to be renamed can be listed as "old_name new_name\n" pairs separated by whitespaces, each on a separate line.

So the old implementation is the one where we only provide the `new_name` and treat the first sample as NORMAL in all cases. This fix uses the alternative approach where we declare BOTH the `new_name` AND the `old_name`. In the original implementation, `bcftools` would always replace the first sample in the VCF with the first sample in the `sample_list.txt` file. In this implementation, `bcftools` only replace `old_name` with `new_name`. If it cannot find `old_name` it will not put in the `new_name`. Additionally, the order of the `sample_list.txt` file no longer matters. All lines in the file can replace any sample in the VCF.

2023-08-21 19:53 UTC, migbro approved these changes
Nice work! I wonder if that matched old/new sample list functionality was always there...much safer!

2023-08-23 17:21 UTC, sickler-alex approved these changes

2023-08-23 21:28 UTC, migbro approved these changes
I think it looks good. We could try a more "surgical" approach, but it'd likely end up being more complicated and probably not worth saving maybe a few hundred bucks over the lost time and effort, which is a greater cost.

2023-08-23 21:37 UTC, merged