📝 🧹Update ref pointers, add pure lancet mode, lceanup deprecated
kids-first/kf-somatic-workflow pull request #184
Opened 2024-05-14 15:03 UTC by migbro

## Description
This started off as a simple refs-pointer update, but since in the near-ish future, we'll be updating Lancet calls, I also updated that functionality and also just deleted a bunch of legacy stuff as clean up. To summarize as a bullet list:
 - Update default sbg file tags
 - Added an input for a user to add existing VCF calls so that Lancet exome+ mode can be run on existing data , instead of having to re-run strelka2 and mutect2 internally
 - Updated the validator logic to look for at least a strelka2/mutect2 internal run or a user to supply vcf files when validating run lancet true
 - Removed a whole bunch of dev and deprecated wfs as they'll exist in old releases if needed
 - Updated README, also updated `doc` which updated formatting

Fixes # BIXU-3657 and BIXU-3655

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/ce1efa41-6577-41ff-a6df-7dd33798311d/
- [ ] Test B

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have committed any related changes to the PR

2024-05-14 17:03 UTC, wongjessica93 approved these changes

2024-05-16 15:17 UTC, dmiller15 commented on workflow/kfdrc-somatic-variant-workflow.cwl
>            $(self.filter(function(e) { return e != null }).map(function(e) { return e.filter(function(i) { return i.basename.search(/(.vcf|.vcf.gz)$/) != -1 })[0] }))
So yeah the `valueFrom` won't play nice with `lancet_input_vcf`. Specifically the `[0]` at the end, you'll only ever end up taking the first VCF from `lancet_input_vcf`.

2024-05-16 15:20 UTC, dmiller15 requested changes
Everything looks good except for the `lancet_input_vcf` integration on that `supplementary_vcf` input. The expression needs to be changed to get _all_ of the VCF rather than just the first one.

2024-05-20 19:15 UTC, migbro commented
New test here: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/fd7cb280-ef05-4efd-99a1-59f753343c4e/
Incorporated collaborative fixes with @dmiller15

2024-05-20 19:22 UTC, dmiller15 approved these changes

2024-05-20 20:37 UTC, merged