🧹 update pubapp
kids-first/kf-somatic-workflow pull request #64
Opened 2020-09-11 16:46 UTC by dmiller15

## Description

The PR cleans up the repo and readme.
It also updates the public app with the new readme and release info.

## Type of change

- [x] documentation update

## How Has This Been Tested?

- [x] New public app passes cwltool validation

**Test Configuration**:
* Environment: cwltool 3.0.20200324120055

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2020-09-11 18:04 UTC, migbro requested changes
The usual app doc vs README, just remove the table from the app doc...unless you want it there to encourage users using the public app, that if they want something less aggressive, to pull from the git repo and use whatever makes sense. That table is really nice, simple, does the job!

2020-09-11 18:04 UTC, migbro commented on workflow/kfdrc-somatic-variant-workflow.cwl
> +  ### Standalone Somatic Workflows
Can probably remove this from app doc

2020-09-11 18:21 UTC, dmiller15 commented on workflow/kfdrc-somatic-variant-workflow.cwl
> +  ### Standalone Somatic Workflows
Makes sense. Removed.

2020-09-16 17:18 UTC, migbro approved these changes
Good for solving Ops teams issues, file IDs will need updating before app pub

2020-09-16 18:30 UTC, dmiller15 commented
Yeah if the fix in #65 works I'll close and remake this PR with updated IDs.

2020-09-17 19:27 UTC, sickler-alex approved these changes

2020-09-18 21:21 UTC, dmiller15 commented
Closing in favor of #66

2020-09-18 21:21 UTC, closed without merging